---
# Source: cloudfnt-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloudfnt-web-test
  labels:
    helm.sh/chart: cloudfnt-web-1.0.0
    app.kubernetes.io/name: cloudfnt-web
    app.kubernetes.io/instance: eeji-cloudfnt-web-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - port: 3333
      targetPort: 9871
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cloudfnt-web
    app.kubernetes.io/instance: eeji-cloudfnt-web-test
---
# Source: cloudfnt-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudfnt-web-test
  labels:
    helm.sh/chart: cloudfnt-web-1.0.0
    app.kubernetes.io/name: cloudfnt-web
    app.kubernetes.io/instance: eeji-cloudfnt-web-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudfnt-web
      app.kubernetes.io/instance: eeji-cloudfnt-web-test
  template:
    metadata:
      labels:
        helm.sh/chart: cloudfnt-web-1.0.0
        app.kubernetes.io/name: cloudfnt-web
        app.kubernetes.io/instance: eeji-cloudfnt-web-test
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: cloudai-gke-runner
      securityContext:
        {}
      containers:
        - name: cloudfnt-web
          securityContext:
            {}
          image: "asia-northeast3-docker.pkg.dev/ineeji-cloudai-test/cloudai-cloudfnt-web/cloudfnt-web:20240430R1__bb1cde8"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "9871"
            - name: REACT_APP_API_SERVER_URL
              value: http://10.0.0.35
          ports:
            - name: http
              containerPort: 9871
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9871
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9871
            initialDelaySeconds: 60
          resources:
            requests:
              cpu: 2000m
              memory: 3Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - cpu-node-pool-ineeji-cloudai-test
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: cloudfnt
---
# Source: cloudfnt-web/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudfnt-web-test
  labels:
    helm.sh/chart: cloudfnt-web-1.0.0
    app.kubernetes.io/name: cloudfnt-web
    app.kubernetes.io/instance: eeji-cloudfnt-web-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    ingressClassName: "gce"
    kubernetes.io/ingress.global-static-ip-name: "eeji-cloudfnt-web-lb-endpoint"
    networking.gke.io/managed-certificates: "eeji-cloudfnt-web-test-cert"
    cloud.google.com/backend-config: '{"default": "cloudfnt-web-test"  }'
spec:
  defaultBackend:
    service:
      name: cloudfnt-web-test
      port:
        number: 3333
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: cloudfnt-web-test
                port:
                  number: 3333
---
# Source: cloudfnt-web/templates/backendconfig.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cloudfnt-web-test
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 60
    healthyThreshold: 3
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 3333
---
# Source: cloudfnt-web/templates/certificate.yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: eeji-cloudfnt-web-test-cert
  labels:
    helm.sh/chart: cloudfnt-web-1.0.0
    app.kubernetes.io/name: cloudfnt-web
    app.kubernetes.io/instance: eeji-cloudfnt-web-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  domains:
    - "test.infinite-optimal.com"
